package view;

public enum IntentEnum {
    CONTRACT_DETAILS,
    CONTRACT_SEARCH,
    CONTRACT_BY_USER,
    CONTRACT_BY_CUSTOMER,
    CONTRACT_STATUS,
    PARTS_BY_CONTRACT,
    PARTS_SPECIFICATIONS,
    PARTS_AVAILABILITY,
    CONTRACTS_BY_PART,
    FAILED_PARTS_BY_CONTRACT,
    FAILED_PARTS_BY_PART,
    HELP_CREATE_CONTRACT,
    UNKNOWN
}